cc_binary(
        name = "orderPizza",
        srcs = ["orderPizza.cc"],
        deps = [
                "//lib:PizzaStore",
                "//lib:Pizza",
                "//lib:PizzaIngredientFactory",
                ],
        )
