cc_binary(
        name = "Order",
        srcs = ["Order.cpp"],
        deps = [
#                "//lib:build-all-files",
                "//lib:Menus",
                "//lib:Waitress",
                ],
        )
